### ISSUE TITLE
Jumping is not mandatory

### ISSUE THREAD

**Issue by jrgfogh** [codethejason/checkers#3]
If a jump is available, the player can make a simple move with another piece.

Instead, jumping should always be mandatory, if a jump is available.

Note that mandatory jumps work partially: The game does not let the user make a simple move with a piece for which a jump is available.

**Comment by codethejason** [comment]
@society765 Can you check why your merge didn't fix this issue?

**Comment by xwang233** [comment]
Hello @jrgfogh , the problem you mentioned was already fixed in a recent merge. I guess you probably clicked the demo from @codethejason 's repo, whose gh-pages is linked to an old commit.

If you want try the demo with a bug-fixed version, you may find that in my repo at https://society765.github.io/checkers-visualize/. The basic logic in my gh-pages is up-to-date and the same as the latest commit in the current repo. Enjoy!

**Comment by codethejason** [comment]
@society765 Thanks, forgot I had another gh-pages branch, will merge that now.
